// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: pkg/frame/frame.proto

package frame

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameData_TYPE int32

const (
	FrameData_USER_DATA FrameData_TYPE = 0
	FrameData_CONN      FrameData_TYPE = 1
	FrameData_CONNRSP   FrameData_TYPE = 2
	FrameData_CLOSE     FrameData_TYPE = 3
	FrameData_HB        FrameData_TYPE = 4
)

// Enum value maps for FrameData_TYPE.
var (
	FrameData_TYPE_name = map[int32]string{
		0: "USER_DATA",
		1: "CONN",
		2: "CONNRSP",
		3: "CLOSE",
		4: "HB",
	}
	FrameData_TYPE_value = map[string]int32{
		"USER_DATA": 0,
		"CONN":      1,
		"CONNRSP":   2,
		"CLOSE":     3,
		"HB":        4,
	}
)

func (x FrameData_TYPE) Enum() *FrameData_TYPE {
	p := new(FrameData_TYPE)
	*p = x
	return p
}

func (x FrameData_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameData_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_frame_frame_proto_enumTypes[0].Descriptor()
}

func (FrameData_TYPE) Type() protoreflect.EnumType {
	return &file_pkg_frame_frame_proto_enumTypes[0]
}

func (x FrameData_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameData_TYPE.Descriptor instead.
func (FrameData_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_frame_frame_proto_rawDescGZIP(), []int{0, 0}
}

type Frame_TYPE int32

const (
	Frame_DATA Frame_TYPE = 0
	Frame_REQ  Frame_TYPE = 1
	Frame_ACK  Frame_TYPE = 2
	Frame_PING Frame_TYPE = 3
	Frame_PONG Frame_TYPE = 4
)

// Enum value maps for Frame_TYPE.
var (
	Frame_TYPE_name = map[int32]string{
		0: "DATA",
		1: "REQ",
		2: "ACK",
		3: "PING",
		4: "PONG",
	}
	Frame_TYPE_value = map[string]int32{
		"DATA": 0,
		"REQ":  1,
		"ACK":  2,
		"PING": 3,
		"PONG": 4,
	}
)

func (x Frame_TYPE) Enum() *Frame_TYPE {
	p := new(Frame_TYPE)
	*p = x
	return p
}

func (x Frame_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Frame_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_frame_frame_proto_enumTypes[1].Descriptor()
}

func (Frame_TYPE) Type() protoreflect.EnumType {
	return &file_pkg_frame_frame_proto_enumTypes[1]
}

func (x Frame_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Frame_TYPE.Descriptor instead.
func (Frame_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_frame_frame_proto_rawDescGZIP(), []int{1, 0}
}

type FrameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Compress bool   `protobuf:"varint,3,opt,name=compress,proto3" json:"compress,omitempty"`
}

func (x *FrameData) Reset() {
	*x = FrameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_frame_frame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameData) ProtoMessage() {}

func (x *FrameData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_frame_frame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameData.ProtoReflect.Descriptor instead.
func (*FrameData) Descriptor() ([]byte, []int) {
	return file_pkg_frame_frame_proto_rawDescGZIP(), []int{0}
}

func (x *FrameData) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *FrameData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FrameData) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     int32      `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Resend   bool       `protobuf:"varint,2,opt,name=resend,proto3" json:"resend,omitempty"`
	Sendtime int64      `protobuf:"varint,3,opt,name=sendtime,proto3" json:"sendtime,omitempty"`
	Id       int32      `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Data     *FrameData `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Dataid   []int32    `protobuf:"varint,6,rep,packed,name=dataid,proto3" json:"dataid,omitempty"`
	Acked    bool       `protobuf:"varint,7,opt,name=acked,proto3" json:"acked,omitempty"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_frame_frame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_frame_frame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_pkg_frame_frame_proto_rawDescGZIP(), []int{1}
}

func (x *Frame) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Frame) GetResend() bool {
	if x != nil {
		return x.Resend
	}
	return false
}

func (x *Frame) GetSendtime() int64 {
	if x != nil {
		return x.Sendtime
	}
	return 0
}

func (x *Frame) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Frame) GetData() *FrameData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Frame) GetDataid() []int32 {
	if x != nil {
		return x.Dataid
	}
	return nil
}

func (x *Frame) GetAcked() bool {
	if x != nil {
		return x.Acked
	}
	return false
}

var File_pkg_frame_frame_proto protoreflect.FileDescriptor

var file_pkg_frame_frame_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2f, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x09, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x22, 0x3f, 0x0a, 0x04, 0x54, 0x59, 0x50,
	0x45, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x43, 0x4f, 0x4e, 0x4e, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f,
	0x4e, 0x4e, 0x52, 0x53, 0x50, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c, 0x4f, 0x53, 0x45,
	0x10, 0x03, 0x12, 0x06, 0x0a, 0x02, 0x48, 0x42, 0x10, 0x04, 0x22, 0xe5, 0x01, 0x0a, 0x05, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x61, 0x74, 0x61, 0x69, 0x64, 0x18, 0x06, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x64, 0x61,
	0x74, 0x61, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x22, 0x36, 0x0a, 0x04, 0x54, 0x59,
	0x50, 0x45, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x41, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x52, 0x45, 0x51, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x43, 0x4b, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f, 0x4e, 0x47,
	0x10, 0x04, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x6b, 0x67, 0x2f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_frame_frame_proto_rawDescOnce sync.Once
	file_pkg_frame_frame_proto_rawDescData = file_pkg_frame_frame_proto_rawDesc
)

func file_pkg_frame_frame_proto_rawDescGZIP() []byte {
	file_pkg_frame_frame_proto_rawDescOnce.Do(func() {
		file_pkg_frame_frame_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_frame_frame_proto_rawDescData)
	})
	return file_pkg_frame_frame_proto_rawDescData
}

var file_pkg_frame_frame_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_frame_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_frame_frame_proto_goTypes = []interface{}{
	(FrameData_TYPE)(0), // 0: FrameData.TYPE
	(Frame_TYPE)(0),     // 1: Frame.TYPE
	(*FrameData)(nil),   // 2: FrameData
	(*Frame)(nil),       // 3: Frame
}
var file_pkg_frame_frame_proto_depIdxs = []int32{
	2, // 0: Frame.data:type_name -> FrameData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_frame_frame_proto_init() }
func file_pkg_frame_frame_proto_init() {
	if File_pkg_frame_frame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_frame_frame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_frame_frame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_frame_frame_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_frame_frame_proto_goTypes,
		DependencyIndexes: file_pkg_frame_frame_proto_depIdxs,
		EnumInfos:         file_pkg_frame_frame_proto_enumTypes,
		MessageInfos:      file_pkg_frame_frame_proto_msgTypes,
	}.Build()
	File_pkg_frame_frame_proto = out.File
	file_pkg_frame_frame_proto_rawDesc = nil
	file_pkg_frame_frame_proto_goTypes = nil
	file_pkg_frame_frame_proto_depIdxs = nil
}
