version: "3.7"

services:
  pingtunnelClient:
    image: pingtunnel:latest
    ports:
      - 1080:1080
    restart: always
    environment:
      - ACTION=client
      - ARGS=-s=172.17.0.1 --key=11223344
